sonar.projectKey=KarthikKumarBA_github-actions-microsite-node-js
sonar.organization=karthikkumarba

sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,dist/**,coverage/**
sonar.coverage.exclusions=tests/**