sonar.projectKey=github-actions-mircosite-node-js_github-actions-mircosite-node-js
sonar.organization=github-actions-mircosite-node-js

sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,dist/**,coverage/**
sonar.coverage.exclusions=tests/**