name: PR CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/reusable-ci.yml
    with:
      version: 1.0.${{ github.run_number }}-SNAPSHOT-pr-${{ github.event.pull_request.number }}
      artifact-name: microsite-1.0.${{ github.run_number }}-SNAPSHOT-pr-${{ github.event.pull_request.number }}

  security:
    name: Security
    uses: ./.github/workflows/reusable-security.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
